### ISSUE TITLE
Support 90 degree snap turning

### ISSUE THREAD

**Issue by ssshake** [SuperV1234/quakevr#16]
Hey I am really enjoying this mod so far except turning left or right makes me sick. The solution to this of course from witnessing this in other games is 90 degree snap turning. 

Would this be something easy to enable and would you be willing to implement it?

**Comment by SuperV1234** [comment]
There are options to enable snap turning and to adjust the angle in the VR settings in-game menu. Have you looked at those?

**Comment by SuperV1234** [comment]
Closing for now, please open again if the settings didn't work for you.
