### ISSUE TITLE
Make holding the button in menu repeat at accelerated rate

### ISSUE THREAD

**Issue by carn1x** [SuperV1234/quakevr#17]
For some reason on my CV1 all the weapon offsets are generally much too large and about a meter above my hand, and editing the offset requires a hell of a lot of button mashing to alter the scale values. The axe is even worse, one of the default offsets seems to be set to 32.000 where as I need it near to zero, meaning 320 button presses! Holding the button down therefore to repeat the input would be greatly appreciated :)

**Comment by carn1x** [comment]
Found that you can hold Off Hand Trigger and press Y/X to do a 10x jump in Weapon Offset X/Y/Z. I guess this might be a debug binding, since it doesn't appear to apply to the Weapon Scale value? Anyway, hopefully this helps somebody else and I suppose satisfies this issue.

**Comment by SuperV1234** [comment]
Reopening to track this and make it more consistent between menus.

**Comment by SuperV1234** [comment]
This is fixed in the upcoming v0.0.4.

**Comment by SuperV1234** [comment]
Fixed in v0.0.4.
