### ISSUE TITLE
v0.0.3 Next/Previous Weapon bindings not working correctly

### ISSUE THREAD

**Issue by carn1x** [SuperV1234/quakevr#18]
I've tried with Default Bindings, with Stoni's binding, and a custom binding by manually remapping "Previous Weapon", none of them seem to do anything. Nothing in game and nothing in the windows terminal.

EDIT: Using Rift CV1

**Comment by carn1x** [comment]
Found something strange, whilst playing and enduring this bug, I had the load out of Shotgun, Double Barrel, Nailgun, Grenade Launcher, and Previous Button binding was working but was only able to select the Double Barrel, nothing else. I could toggle between Axe and Double Barrel only using the Next/Previous bindings.

**Comment by carn1x** [comment]
I decided to start from scratch: Wipe the entire Quake folder, redownload, install only v0.0.3 over the top. Next/Previous Weapon still malfunctioning to the point of being unusable.

**Comment by Fuji808** [comment]
I can confirm that previous/next weapon is borked. I can't swap weapons at all. Pressing either switches me to the axe and then I can't swap to any other weapon, with a message alerting me that there is "No Weapon" despite me having the shotgun and nail gun. 

Using WMR, Samsung Odyssey+, 0.0.3 QuakeVR release.

**Comment by SuperV1234** [comment]
@carn1x @Fuji808: the upcoming version completely rewrote the way weapons are managed. Would you be willing to test a pre-release version and see if that works for you? Discord would work well for me, my tag is vee#7461

**Comment by carn1x** [comment]
> @carn1x @Fuji808: the upcoming version completely rewrote the way weapons are managed. Would you be willing to test a pre-release version and see if that works for you? Discord would work well for me, my tag is vee#7461

Happy to help once the toddler goes to bed, PMed on Discord.

**Comment by SuperV1234** [comment]
This is fixed in the upcoming v0.0.4.

**Comment by SuperV1234** [comment]
Fixed in v0.0.4.
