### ISSUE TITLE
Jump action seems to work inconsistently when facing/standing near a wall

### ISSUE THREAD

**Issue by carn1x** [SuperV1234/quakevr#21]
When right up against and facing a wall, pressing jump seems to be inconsistent, almost like the wall is somehow blocking the jump, however button mashing jump still seems to be semi-successful so I can't tell what's going on. However stepping back into open space makes jump much more reliable.

**Comment by SuperV1234** [comment]
This is fixed in the upcoming v0.0.4.

**Comment by SuperV1234** [comment]
Fixed in v0.0.4.
