### ISSUE TITLE
"Framebuffer incomplete" error 

### ISSUE THREAD

**Issue by BleepBloop32** [SuperV1234/quakevr#23]
I get this message in the cmd and my game does not display properly, I can see the menu card way down by my nose and cannot get into gameplay.

I have a Ryzen 5 3600, RX 5700, and using the HTC Vive.

**Comment by carn1x** [comment]
Duplicate of #10 ?

**Comment by BleepBloop32** [comment]
I tried running the game not in VR at first like you did but I still got the error

**Comment by carn1x** [comment]
My fix for this was to edit the `id1/config.cfg` file provided by the mod and change `msaa` value to something less than 9.

**Comment by SuperV1234** [comment]
Closing as duplicate of #10. This is fixed in the upcoming v0.0.4. As a workaround, set the `vr_msaa` cvar in `config.cfg` to `0` or `1`.
