### ISSUE TITLE
Motion controller controlled in-game menu

### ISSUE THREAD

**Issue by VsevolodGolovanov** [SuperV1234/quakevr#27]
The in-game menu seems to be only keyboard controllable. Would nice to be able to use motion controllers for it.

**Comment by carn1x** [comment]
Similar to my comment here https://github.com/SuperV1234/quakevr/issues/28#issuecomment-622364569, you can bind a button to menu with SteamVR bindings, you're possibly missing that too.

**Comment by VsevolodGolovanov** [comment]
Basically a duplicate of #28.
