### ISSUE TITLE
Provide default bindings for WMR

### ISSUE THREAD

**Issue by VsevolodGolovanov** [SuperV1234/quakevr#28]
Joysticks don't do anything.

**Comment by VsevolodGolovanov** [comment]
Unless I missed it in options? I assume it's enable by default. I tried disabling teleport, but that didn't help.

**Comment by carn1x** [comment]
@VsevolodGolovanov are you familiar with SteamVR Binding UI? It is likely your bindings are not set. For example see https://www.youtube.com/watch?v=s0H_4kyeWLw

**Comment by VsevolodGolovanov** [comment]
Yes, the problem is with the default bindings. Ideally QuakeVR would provide them.

**Comment by SuperV1234** [comment]
If I had more than one HMD everything would be easier... Right now, I have to rely on Quake VR players to provide these defaults. Can you try these ones out and see if they work for you? If so, I will include them with v0.0.5. If you improve them, please share @VsevolodGolovanov 

[bindings_holographic.zip](https://github.com/SuperV1234/quakevr/files/4589799/bindings_holographic.zip)

**Comment by VsevolodGolovanov** [comment]
These are the same bindings that are already bundled with the 0.0.4 release - the ones with the described problems. I thought there were no default bindings, but I was wrong.

Someone posted better bindings to the Steam workshop on May 1st, but they still have problems: no joystick deadzones, can't navigate menu properly (the joystick's axis are mapped to the menu items so that joystick down = "Multi Player" selected, let go = joystick middle = back to "Single Player").
I'd improve them but I'm not sure how to do this menu stuff.

**Comment by SuperV1234** [comment]
@VsevolodGolovanov: at the moment the menu keys are hardcoded to game keys. These are the bindings:

- Left joystick up/down -> menu navigation up/down
- Jump -> enter
- Escape -> go back
- Next off-hand weapon -> decrease
- Next main hand weapon -> increase

**Comment by SuperV1234** [comment]
I will look into having a separate set of actions for menus in v0.0.5.

**Comment by SuperV1234** [comment]
v0.0.5 comes with WMR bindings and has separate action sets for menu navigation and in-game actions.
