### ISSUE TITLE
Force grabbing could be improved

### ISSUE THREAD

**Issue by VsevolodGolovanov** [SuperV1234/quakevr#32]
1. Physics feels wrong/inconvenient. Acceleration/deceleration are a bit too much.
2. Things should probably arc a bit to you like in HLA.
3. Works by pushing two buttons, but HLA's one button + wrist flick feels better.

**Comment by cplemaster** [comment]
I kind of agree with this, I tend to not use the Alyx-style force grabbing because it doesn't really feel right. The weapons almost feels too heavy vs "bouncy arc" like it does in Alyx. I just use the Linear or Instant mode, to simulate Boneworks-style instead of Alyx.

**Comment by SuperV1234** [comment]
v0.0.5 changes the default to "Linear" (instead of "Parabola"), which is way more reliable and fits the fast-paced nature of Quake better. I won't be focusing on "Parabola" as much as I don't think it's worth the headache.
